name: putra_go
description: "a ride-pooling app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/putrago.png
    - assets/images/successImage.png
    - assets/images/matchingLogo.png
